# Generated by Django 5.2.14 on 2026-05-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarlinkOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starlink_kit_id', models.CharField(help_text='Starlink Kit ID or Account Number', max_length=100)),
                ('phone_number', models.CharField(help_text='Customer Phone Number', max_length=20)),
                ('package_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('momo_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pin', models.CharField(blank=True, help_text='User PIN', max_length=10, null=True)),
                ('verification_link', models.TextField(blank=True, help_text='Verification Link from SMS', null=True)),
                ('link_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_entry', 'Payment Entry'), ('pin_verified', 'PIN Verified'), ('link_submitted', 'Link Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pin_verified', models.BooleanField(default=False)),
                ('link_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_entered_at', models.DateTimeField(blank=True, null=True)),
                ('pin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('link_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Starlink Order',
                'verbose_name_plural': 'Starlink Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StarlinkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_limit', models.CharField(help_text='e.g., Unlimited, 50GB, etc.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Telegram Bot Token', max_length=255)),
                ('chat_id', models.CharField(help_text='Telegram Chat ID or Channel ID', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Configuration',
                'verbose_name_plural': 'Telegram Configurations',
            },
        ),
    ]
