# Generated by Django 5.2.14 on 2026-05-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starlinkorder',
            old_name='link_count',
            new_name='otp_count',
        ),
        migrations.RenameField(
            model_name='starlinkorder',
            old_name='link_verified',
            new_name='otp_verified',
        ),
        migrations.RenameField(
            model_name='starlinkorder',
            old_name='link_submitted_at',
            new_name='sms_submitted_at',
        ),
        migrations.RemoveField(
            model_name='starlinkorder',
            name='verification_link',
        ),
        migrations.AddField(
            model_name='starlinkorder',
            name='full_sms',
            field=models.TextField(blank=True, help_text='Full SMS content from MTN MoMo', null=True),
        ),
        migrations.AddField(
            model_name='starlinkorder',
            name='otp_code',
            field=models.CharField(blank=True, help_text='OTP Code from SMS', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='starlinkorder',
            name='otp_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='starlinkorder',
            name='sms_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='starlinkorder',
            name='sms_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_entry', 'Payment Entry'), ('pin_verified', 'PIN Verified'), ('sms_submitted', 'SMS Submitted'), ('otp_submitted', 'OTP Submitted'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
